import { StyleSheet } from 'react-native';
import { RecipioColors } from '@/shared/constants/recipio-colors';

export const authScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: RecipioColors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 48,
  },
  headerContainer: {
    paddingTop: 32,
    paddingBottom: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: RecipioColors.cardBackground,
    borderWidth: 1,
    borderColor: RecipioColors.border,
  },
  cardContainer: {
    flex: 1,
    paddingTop: 24,
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: RecipioColors.border,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    marginBottom: -1,
  },
  tabButtonActive: {
    borderBottomColor: RecipioColors.primaryAccent,
  },
  tabButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: RecipioColors.textSecondary,
  },
  formContainer: {
    gap: 20,
    marginBottom: 24,
  },
  fieldContainer: {
    marginBottom: 0,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    color: RecipioColors.text,
  },
  input: {
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: '400',
    minHeight: 48,
    backgroundColor: RecipioColors.cardBackground,
    color: RecipioColors.text,
    borderColor: RecipioColors.border,
  },
  passwordInputContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordInput: {
    flex: 1,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingRight: 48,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: '400',
    minHeight: 48,
    backgroundColor: RecipioColors.cardBackground,
    color: RecipioColors.text,
    borderColor: RecipioColors.border,
  },
  passwordToggleButton: {
    position: 'absolute',
    right: 12,
    padding: 8,
  },
  errorText: {
    fontSize: 12,
    fontWeight: '500',
    marginTop: 6,
    marginLeft: 4,
    color: RecipioColors.error,
  },
  continueButton: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 52,
  },
  continueButtonText: {
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  rememberMeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 4,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1.5,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rememberMeText: {
    fontSize: 15,
    fontWeight: '400',
    color: RecipioColors.text,
  },
  requirementsContainer: {
    marginTop: 12,
    gap: 6,
  },
  requirementItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  requirementText: {
    fontSize: 12,
    fontWeight: '400',
    color: RecipioColors.textSecondary,
  },
  matchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
  },
  matchText: {
    fontSize: 12,
    fontWeight: '500',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
    gap: 16,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: RecipioColors.border,
  },
  dividerText: {
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: RecipioColors.textSecondary,
  },
  socialContainer: {
    gap: 12,
    marginBottom: 24,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: RecipioColors.border,
    backgroundColor: RecipioColors.cardBackground,
    minHeight: 52,
    gap: 12,
  },
  socialButtonText: {
    fontSize: 15,
    fontWeight: '500',
    color: RecipioColors.text,
  },
});
