import { Platform, StyleSheet } from 'react-native';
import type { RecipioColorsPalette } from '@/shared/constants/recipio-colors';

export function createRecipeDetailStyles(colors: RecipioColorsPalette) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.cardBackground,
    },
    header: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: Platform.OS === 'web' ? 12 : 44,
      paddingHorizontal: 20,
      zIndex: 10,
    },
    headerBtn: {
      width: 44,
      height: 44,
      minWidth: 44,
      minHeight: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 11,
    },
    hero: {
      width: '100%',
      height: 280,
      backgroundColor: colors.border,
    },
    scroll: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 100,
    },
    title: {
      fontSize: 24,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 12,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      marginBottom: 16,
    },
    metaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    metaText: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    servingsRow: {
      marginBottom: 20,
    },
    servingsLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
      letterSpacing: 0.5,
      marginBottom: 10,
    },
    servingsPills: {
      flexDirection: 'row',
      gap: 10,
    },
    pill: {
      minWidth: 48,
      height: 44,
      paddingHorizontal: 16,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.cardBackground,
    },
    pillSelected: {
      borderColor: colors.primaryAccent,
      backgroundColor: colors.primaryAccent,
    },
    pillText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    pillTextSelected: {
      color: '#FFFFFF',
    },
    description: {
      fontSize: 15,
      color: colors.text,
      lineHeight: 22,
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primaryAccent,
      marginBottom: 12,
    },
    nutritionRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 28,
    },
    nutritionCard: {
      flex: 1,
      backgroundColor: colors.cardBackground,
      borderRadius: 12,
      padding: 14,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    nutritionCardKcal: {
      borderColor: colors.primaryAccent,
    },
    nutritionValue: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    nutritionValueKcal: {
      color: colors.primaryAccent,
    },
    nutritionLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textSecondary,
      marginTop: 4,
      letterSpacing: 0.3,
    },
    nutritionLabelKcal: {
      color: colors.primaryAccent,
    },
    ingredientsHeader: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    ingredientsTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    ingredientsCount: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    ingredientRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.cardBackground,
      borderRadius: 10,
      padding: 14,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    ingredientName: {
      fontSize: 15,
      color: colors.text,
      fontWeight: '500',
    },
    stepsSectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      marginTop: 24,
      marginBottom: 12,
    },
    stepRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 14,
      gap: 12,
    },
    stepNumber: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.primaryAccent,
      justifyContent: 'center',
      alignItems: 'center',
    },
    stepNumberText: {
      fontSize: 13,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    stepText: {
      flex: 1,
      fontSize: 15,
      color: colors.text,
      lineHeight: 22,
    },
    chefTip: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.cardBackground,
      borderRadius: 12,
      padding: 16,
      paddingLeft: 14,
      marginTop: 24,
      gap: 12,
      borderWidth: 0,
      borderLeftWidth: 4,
      borderLeftColor: colors.primaryAccent,
    },
    chefTipText: {
      flex: 1,
      fontSize: 14,
      color: colors.text,
      lineHeight: 21,
    },
    cta: {
      height: 54,
      backgroundColor: colors.primaryAccent,
      borderRadius: 12,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 28,
      gap: 10,
    },
    ctaText: {
      fontSize: 17,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    error: {
      padding: 40,
      alignItems: 'center',
    },
    errorText: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: 'center',
    },
  });
}
