import { StyleSheet } from 'react-native';
import { RecipioColors } from '@/shared/constants/recipio-colors';
import { Platform } from 'react-native';

export const recipeDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: RecipioColors.cardBackground,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: Platform.OS === 'web' ? 12 : 44,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  headerBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  hero: {
    width: '100%',
    height: 280,
    backgroundColor: RecipioColors.border,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: RecipioColors.text,
    marginBottom: 12,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 16,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontSize: 14,
    color: RecipioColors.textSecondary,
  },
  servingsRow: {
    marginBottom: 20,
  },
  servingsLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: RecipioColors.textSecondary,
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  servingsPills: {
    flexDirection: 'row',
    gap: 10,
  },
  pill: {
    minWidth: 48,
    height: 44,
    paddingHorizontal: 16,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: RecipioColors.border,
    backgroundColor: RecipioColors.cardBackground,
  },
  pillSelected: {
    borderColor: RecipioColors.primaryAccent,
    backgroundColor: RecipioColors.primaryAccent,
  },
  pillText: {
    fontSize: 15,
    fontWeight: '600',
    color: RecipioColors.textSecondary,
  },
  pillTextSelected: {
    color: '#FFFFFF',
  },
  description: {
    fontSize: 15,
    color: RecipioColors.text,
    lineHeight: 22,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: RecipioColors.primaryAccent,
    marginBottom: 12,
  },
  nutritionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 28,
  },
  nutritionCard: {
    flex: 1,
    backgroundColor: RecipioColors.cardBackground,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: RecipioColors.border,
  },
  nutritionCardKcal: {
    borderColor: RecipioColors.primaryAccent,
  },
  nutritionValue: {
    fontSize: 16,
    fontWeight: '700',
    color: RecipioColors.text,
  },
  nutritionValueKcal: {
    color: RecipioColors.primaryAccent,
  },
  nutritionLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: RecipioColors.textSecondary,
    marginTop: 4,
    letterSpacing: 0.3,
  },
  nutritionLabelKcal: {
    color: RecipioColors.primaryAccent,
  },
  ingredientsHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  ingredientsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: RecipioColors.text,
  },
  ingredientsCount: {
    fontSize: 14,
    color: RecipioColors.textSecondary,
    fontWeight: '500',
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: RecipioColors.cardBackground,
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: RecipioColors.border,
  },
  ingredientName: {
    fontSize: 15,
    color: RecipioColors.text,
    fontWeight: '500',
  },
  stepsSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: RecipioColors.text,
    marginTop: 24,
    marginBottom: 12,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
    gap: 12,
  },
  stepNumber: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: RecipioColors.primaryAccent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepNumberText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  stepText: {
    flex: 1,
    fontSize: 15,
    color: RecipioColors.text,
    lineHeight: 22,
  },
  chefTip: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: RecipioColors.cardBackground,
    borderRadius: 12,
    padding: 16,
    paddingLeft: 14,
    marginTop: 24,
    gap: 12,
    borderWidth: 0,
    borderLeftWidth: 4,
    borderLeftColor: RecipioColors.primaryAccent,
  },
  chefTipText: {
    flex: 1,
    fontSize: 14,
    color: RecipioColors.text,
    lineHeight: 21,
  },
  cta: {
    height: 54,
    backgroundColor: RecipioColors.primaryAccent,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 28,
    gap: 10,
  },
  ctaText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  error: {
    padding: 40,
    alignItems: 'center',
  },
  errorText: {
    fontSize: 15,
    color: RecipioColors.textSecondary,
    textAlign: 'center',
  },
});
