import { Platform, StyleSheet } from 'react-native';
import { getRecipioColors, type RecipioColorsPalette } from '@/shared/constants/recipio-colors';

export function createCookingGuideStyles(colors: RecipioColorsPalette | null | undefined) {
  const c = colors ?? getRecipioColors(false);
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Platform.OS === 'web' ? 12 : 44,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: c.cardBackground,
    borderBottomWidth: 1,
    borderBottomColor: c.border,
  },
  headerBtn: {
    width: 44,
    height: 44,
    minWidth: 44,
    minHeight: 44,
    borderRadius: 22,
    backgroundColor: c.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: c.text,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
  },
  stepImageContainer: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    backgroundColor: c.border,
    overflow: 'hidden',
    marginBottom: 20,
  },
  stepImage: {
    width: '100%',
    height: '100%',
  },
  stepLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: c.primaryAccent,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  stepText: {
    fontSize: 17,
    color: c.text,
    lineHeight: 26,
    marginBottom: 20,
  },
  chefTipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: c.cardBackground,
    borderRadius: 12,
    padding: 16,
    paddingLeft: 14,
    marginBottom: 20,
    gap: 12,
    borderWidth: 0,
    borderLeftWidth: 4,
    borderLeftColor: c.primaryAccent,
  },
  chefTipLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: c.primaryAccent,
    marginBottom: 6,
  },
  chefTipText: {
    flex: 1,
    fontSize: 14,
    color: c.text,
    lineHeight: 21,
  },
  notesSection: {
    marginTop: 16,
    marginBottom: 24,
  },
  notesLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: c.textSecondary,
    marginBottom: 8,
  },
  notesInput: {
    backgroundColor: c.cardBackground,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: c.border,
    padding: 14,
    fontSize: 15,
    color: c.text,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    gap: 6,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: c.border,
  },
  progressDotActive: {
    width: 24,
    borderRadius: 12,
    backgroundColor: c.primaryAccent,
  },
  navRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  navButton: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: c.border,
    backgroundColor: c.cardBackground,
  },
  navButtonPrimary: {
    backgroundColor: c.primaryAccent,
    borderColor: c.primaryAccent,
  },
  navButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: c.text,
  },
  navButtonTextPrimary: {
    color: '#FFFFFF',
  },
  completeWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
  },
  completeIconRing: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: 'rgba(255, 87, 34, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
  },
  completeIconInner: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: c.cardBackground,
    borderWidth: 2,
    borderColor: c.primaryAccent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completeHeadline: {
    fontSize: 26,
    fontWeight: '700',
    color: c.text,
    marginBottom: 12,
    textAlign: 'center',
  },
  completeRecipeName: {
    fontSize: 18,
    fontWeight: '600',
    color: c.primaryAccent,
    textAlign: 'center',
    marginBottom: 8,
    paddingHorizontal: 16,
  },
  completeSubline: {
    fontSize: 15,
    color: c.textSecondary,
    textAlign: 'center',
    marginBottom: 36,
    lineHeight: 22,
  },
  completeButton: {
    width: '100%',
    height: 52,
    borderRadius: 14,
    backgroundColor: c.primaryAccent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completeButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  error: {
    padding: 40,
    alignItems: 'center',
  },
  errorText: {
    fontSize: 15,
    color: c.textSecondary,
    textAlign: 'center',
  },
  });
}

export type CookingGuideStyles = ReturnType<typeof createCookingGuideStyles>;
